on:
  push:
  pull_request:

name: ci

jobs:
  build:
    name: Build
    strategy:
      matrix:
        include:
          - platform: "ubuntu-latest"
            elan_url : "https://github.com/leanprover/elan/releases/download/v1.4.2/elan-x86_64-unknown-linux-gnu.tar.gz"
          - platform: "macos-latest"
            elan_url: "https://github.com/leanprover/elan/releases/download/v2.0.1/elan-x86_64-apple-darwin.tar.gz"
    runs-on: ${{ matrix.platform }}
    steps:
      - name: install elan
        run: |
          set -o pipefail
          curl -sSfL ${{ matrix.elan_url }} | tar xz
          ./elan-init -y --default-toolchain none
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - uses: actions/checkout@v3

      - name: build socket.lean
        run: lake build
